server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:honorhub;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

app:
  jwt:
    secret: "replace-with-a-long-random-secret-string-32+chars"
    expiryMillis: 86400000   # 24h
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"